# Python Review

SHort review about some core concepts in Python exemplified by objects in the NumPy library.
Goals:

- recall basic Pyuthon vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform soecific tasks in our programs. It can be a single file or multiple files.

**NumPy:**

- core library for numerical comuting in Python
- many of libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's inport NumPy with tis **standard abbreviation** `np`:

In [ ]:
import numpy as np

(esc + M twice _> convert cell to markdown cell)

## Variables

**variables:** a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our Jupiter notebook:

In [4]:
# Run a cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
